version: '3'
services:
    webserver:
        build:
            context: ./nginx
        image: nginx
        container_name: webserver
        restart: unless-stopped
        ports:
            - "80:80"
        depends_on:
            - server_api
        networks:
            - project-network
        
    server_api:
        build:
            context: ./api
        image: server_api_image
        container_name: server_api_container
        restart: unless-stopped
        depends_on:
            - database
        links:
            - "database"
        env_file: .env
        expose:
            - ${API_PORT}
        volumes:
            - .:/api
        networks:
            - project-network
        environment:
            - DATABASE_HOST=database
            - DATABASE_USERNAME=postgres
            - DATABASE_PASSWORD=admin
            - DATABASE_NAME=shipments
            - WAIT_HOSTS:database:5432
            - WAIT_HOSTS_TIMEOUT:300
            - WAIT_SLEEP_INTERVAL:300
            - WAIT_HOST_CONNECT_TIMEOUT:300

    database:
        build:
            context: ./postgresql
        image: postgresql
        container_name: postgres_container
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=shipments
        restart: unless-stopped
        expose:
            - "5432"
        networks:
            - project-network

networks:
  project-network:
    name: project-network
    driver: bridge